const instruments=[{name:'Synth keys',icon:'♩',type:'piano',color:'#6957e8'},{name:'Grand piano',icon:'♬',type:'piano',color:'#8b78ef'},{name:'Electric guitar',icon:'⚡',type:'guitar',color:'#ff6ca8'},{name:'Acoustic guitar',icon:'♢',type:'guitar',color:'#eaa947'},{name:'Deep bass',icon:'◖',type:'bass',color:'#45c6b3'},{name:'Drum kit',icon:'◉',type:'drums',color:'#ed8d53'},{name:'Harp',icon:'♮',type:'harp',color:'#e8b84c'},{name:'Violin',icon:'♩',type:'strings',color:'#e97593'},{name:'Viola',icon:'♪',type:'strings',color:'#ca75d8'},{name:'Flute',icon:'♧',type:'wind',color:'#50c5dc'},{name:'Clarinet',icon:'◒',type:'wind',color:'#4c81d9'},{name:'Dream vox',icon:'☄',type:'voice',color:'#f06ca8'}];
const state={projectName:'Midnight Bloom',instrument:0,tempo:108,playing:false,tracks:[['Beat machine','Drum kit','▦'],['Bubble bass','Deep bass','◖'],['Glow keys','Synth keys','♩'],['Dream vox','Dream vox','☄']],steps:[[1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0],[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],[0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1]],chordScore:0,recordings:[]};
let audioCtx,mediaRecorder,recordingChunks=[],loopTimer;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function audio(){audioCtx??=new (window.AudioContext||window.webkitAudioContext)();return audioCtx}
function tone(freq,duration=.28,type='sine',when=0,volume=.09){const c=audio(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0.0001,c.currentTime+when);g.gain.exponentialRampToValueAtTime(volume,c.currentTime+when+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+when+duration);o.connect(g).connect(c.destination);o.start(c.currentTime+when);o.stop(c.currentTime+when+duration+.03)}
function noteForKey(key){return {a:261.63,s:293.66,d:329.63,f:349.23,g:392,h:440,j:493.88,k:523.25}[key.toLowerCase()]}
function playNote(freq,type='sine'){tone(freq,.5,type,0,.12)}
function renderTracks(){const list=$('#trackList');list.innerHTML=state.tracks.map((t,i)=>`<div class="track"><span class="track-color">${t[2]}</span><div class="track-info"><b>${t[0]}</b><span>${t[1]}</span></div><div class="track-meter"><i style="width:${[84,61,72,42][i%4]}%"></i></div><button aria-label="Mute ${t[0]}" class="mute">◖</button></div>`).join('')}
function renderProjects(){const list=$('#projectList');list.innerHTML=`<div class="project-item current"><i class="project-dot"></i>${state.projectName}</div><div class="project-item"><i class="project-dot blue"></i>Sunday sketches</div>`}
function renderSequencer(){const labels=['KICK','SNARE','HAT','VOX'];$('#sequencer').innerHTML=state.steps.map((row,r)=>`<div class="sequencer-row"><span class="row-label">${labels[r]}</span>${row.map((on,c)=>`<button class="step ${on?'active':''}" data-row="${r}" data-col="${c}" aria-label="${labels[r]} step ${c+1}"></button>`).join('')}</div>`).join('')}
function renderInstruments(){const grid=$('#instrumentGrid');grid.innerHTML=instruments.map((x,i)=>`<button class="instrument-tile ${i===state.instrument?'active':''}" data-inst="${i}"><span class="inst-icon" style="color:${x.color}">${x.icon}</span><b>${x.name}</b><small>${x.type}</small></button>`).join('');$('#instrumentCount').textContent=`${instruments.length} sounds`}
function renderPlayable(){const x=instruments[state.instrument];$('#playableTitle').textContent=x.name;$('#currentInstrument').textContent=x.name;$('#instrumentIcon').textContent=x.icon;const p=$('#playableInstrument');$('#guitarControls').classList.toggle('hidden',x.type!=='guitar');if(x.type==='piano'||x.type==='strings'||x.type==='harp'||x.type==='wind'||x.type==='voice'){const notes=[261.63,293.66,329.63,349.23,392,440,493.88,523.25,587.33,659.25,698.46,783.99];p.innerHTML=`<div class="piano">${notes.map((n,i)=>`<button class="piano-key ${[1,3,6,8,10].includes(i)?'black':''}" data-freq="${n}">${String.fromCharCode(65+(i%8))}</button>`).join('')}</div>`}else{const glyph=x.type==='drums'?['●','◉','✦','◌','◆','✹','◍','✧']:['✦','⚡','◈','✹','✧','✦','◈','⚡'];p.innerHTML=`<div class="pad-grid">${glyph.map((g,i)=>`<button class="sound-pad" data-pad="${i}">${g}</button>`).join('')}</div>`}}
function setInstrument(i){state.instrument=i;renderInstruments();renderPlayable();toast(`${instruments[i].name} selected`);save(false)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function save(show=true){localStorage.setItem('neonJamLab',JSON.stringify(state));$('#savedState').textContent='● Saved just now';if(show)toast('Project saved locally')}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('neonJamLab'))||{})}catch{}renderTracks();renderSequencer();renderInstruments();renderPlayable();renderProjects();$('#tempoValue').textContent=state.tempo;$('#projectNameTop').textContent=state.projectName}
function switchView(name){$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'))}
function playLoop(){state.playing=!state.playing;$('#playLoop').textContent=state.playing?'Ⅱ':'▶';$('#playAllBtn').innerHTML=state.playing?'<span class="play-symbol">Ⅱ</span> Pause jam <kbd>Space</kbd>':'<span class="play-symbol">▶</span> Play jam <kbd>Space</kbd>';if(state.playing){let column=0;loopTimer=setInterval(()=>{state.steps.forEach((row,r)=>{if(row[column]){const freqs=[90,180,330,520];tone(freqs[r],.13,r===2?'square':'sine',0,.06)}});column=(column+1)%16},150)}else clearInterval(loopTimer)}
function playChord(kind){const root=kind==='major'?261.63:220;[root,root*(kind==='major'?1.25:1.189),root*1.5].forEach((f,i)=>tone(f,.65,'triangle',i*.04,.08))}
function exportProject(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.projectName.replaceAll(' ','-').toLowerCase()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Project downloaded')}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)switchView(nav.dataset.view);const target=e.target.closest('[data-view-target]');if(target)switchView(target.dataset.viewTarget);const step=e.target.closest('.step');if(step){const r=+step.dataset.row,c=+step.dataset.col;state.steps[r][c]^=1;renderSequencer();save(false)}const inst=e.target.closest('[data-inst]');if(inst)setInstrument(+inst.dataset.inst);const key=e.target.closest('[data-freq]');if(key){playNote(+key.dataset.freq,instruments[state.instrument].type==='strings'?'triangle':'sine');key.classList.add('active');setTimeout(()=>key.classList.remove('active'),180)}const pad=e.target.closest('[data-pad]');if(pad){playNote(120+ +pad.dataset.pad*55,'square');pad.classList.add('active');setTimeout(()=>pad.classList.remove('active'),180)}const fx=e.target.closest('[data-fx]');if(fx){fx.classList.toggle('on');toast(`${fx.dataset.fx} ${fx.classList.contains('on')?'on':'off'}`)}const ans=e.target.closest('[data-answer]');if(ans){const correct=ans.dataset.answer===window.currentChord;$$('[data-answer]').forEach(b=>b.classList.remove('correct','wrong'));ans.classList.add(correct?'correct':'wrong');if(correct){state.chordScore+=10;$('#pitchScore').textContent=`${state.chordScore} pts`;$('#pitchFeedback').textContent='That one landed! You heard the feeling.'}else $('#pitchFeedback').textContent='Try again—listen for bright vs. shadowy.'}const tri=e.target.closest('[data-note]');if(tri){tri.classList.toggle('selected');const selected=$$('.triad-notes button.selected').map(x=>x.dataset.note);$('#triadFeedback').textContent=selected.length===3?(selected.sort().join(' · ')==='C · E · G'?'Beautiful major triad!':'Try C, E, and G for a sunny stack.'):`${selected.length}/3 notes chosen`;if(selected.length===3&&selected.sort().join('')==='CEG')selected.forEach((n,i)=>tone({C:261.63,E:329.63,G:392}[n],.4,'triangle',i*.12,.08))}const interval=e.target.closest('[data-interval]');if(interval){const correct=interval.dataset.interval===window.currentInterval;interval.classList.add(correct?'correct':'wrong');$('#intervalFeedback').textContent=correct?'Nice—your ears caught the distance.':'Listen again and compare how wide the leap feels.'}});
$('#playLoop').onclick=playLoop;$('#playAllBtn').onclick=playLoop;$('#clearLoop').onclick=()=>{state.steps=state.steps.map(r=>r.map(()=>0));renderSequencer();save(false)};$('#randomizeBtn').onclick=()=>{state.steps=state.steps.map(r=>r.map(()=>Math.random()>.68?1:0));renderSequencer();toast('A fresh groove appeared');save(false)};$('#tempoDown').onclick=()=>{state.tempo=Math.max(60,state.tempo-4);$('#tempoValue').textContent=state.tempo;save(false)};$('#tempoUp').onclick=()=>{state.tempo=Math.min(180,state.tempo+4);$('#tempoValue').textContent=state.tempo;save(false)};$('#newProjectBtn').onclick=()=>{state.projectName='Starlight Sketch';state.steps=state.steps.map(r=>r.map(()=>0));$('#projectNameTop').textContent=state.projectName;renderSequencer();save();toast('Fresh project started')};$('#exportBtn').onclick=exportProject;$('#importBtn').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{Object.assign(state,JSON.parse(reader.result));load();toast('Project imported')}catch{toast('That file could not be opened')}};reader.readAsText(f)};
$('#recordBtn').onclick=async()=>{if(mediaRecorder?.state==='recording'){mediaRecorder.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);recordingChunks=[];mediaRecorder.ondataavailable=e=>recordingChunks.push(e.data);mediaRecorder.onstop=()=>{const url=URL.createObjectURL(new Blob(recordingChunks,{type:'audio/webm'}));state.recordings.push({name:`Vocal take ${state.recordings.length+1}`,url});$('#recordingStatus').innerHTML='✓ Take captured';$('#recordBtn').innerHTML='<span>●</span> Record another';stream.getTracks().forEach(t=>t.stop());save()};mediaRecorder.start();$('#recordBtn').innerHTML='<span>■</span> Stop recording';$('#recordingStatus').textContent='Listening…'}catch{$('#recordingStatus').textContent='Mic permission needed';toast('Allow microphone access to record')}};
$('#playChord').onclick=()=>{window.currentChord=Math.random()>.5?'major':'minor';playChord(window.currentChord);$('#pitchFeedback').textContent='Now choose the feeling you heard.'};$('#playTriad').onclick=()=>{const selected=$$('.triad-notes button.selected').map(x=>x.dataset.note);const triadFreqs={C:261.63,E:329.63,G:392,A:440};if(selected.length===3)selected.forEach((n,i)=>tone(triadFreqs[n]||0,.4,'triangle',i*.12,.08));else toast('Pick three notes first')};$('#playInterval').onclick=()=>{window.currentInterval=Math.random()>.5?'step':'leap';const first=261.63; tone(first,.3,'sine',0,.1);tone(window.currentInterval==='step'?293.66:392,.4,'sine',.4,.1);$('#intervalFeedback').textContent='Which distance did you hear?'};window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();playLoop()}const f=noteForKey(e.key);if(f)playNote(f,instruments[state.instrument].type==='strings'?'triangle':'sine')});load();

// Game upgrades: fresh rounds, more distinct harmony, and a playable falling-tile mode.
function resetAnswerButtons(selector){$$(selector).forEach(b=>b.classList.remove('correct','wrong'))}
function addResetButton(parent,handler){const b=document.createElement('button');b.className='reset-game';b.textContent='↻ New round';b.onclick=handler;parent.appendChild(b)}
function resetPitchRound(){window.currentChord=null;resetAnswerButtons('[data-answer]');$('#pitchFeedback').textContent='Press hear, then choose major or minor.';$('#playChord').textContent='▶  Hear a new chord'}
function resetTriadRound(){$$('.triad-notes button').forEach(b=>b.classList.remove('selected'));$('#triadFeedback').textContent='Pick three notes, then play your triad.'}
function resetIntervalRound(){window.currentInterval=null;resetAnswerButtons('[data-interval]');$('#intervalFeedback').textContent='Press play, then choose the distance.'}
function clearerChord(kind){const root=kind==='major'?261.63:220;const third=kind==='major'?329.63:261.63;const fifth=kind==='major'?392:329.63;[root,third,fifth].forEach((f,i)=>tone(f,.85,'sine',i*.22,.13));tone(root/2,.7,'triangle',0,.08)}
playChord=clearerChord;
function makeGameUpgrades(){const pitch=$('#playChord').parentElement;addResetButton(pitch,resetPitchRound);const triad=$('#playTriad').parentElement;addResetButton(triad,resetTriadRound);const interval=$('#playInterval').parentElement;addResetButton(interval,resetIntervalRound);const card=document.createElement('section');card.className='card game-card tiles-game';card.innerHTML=`<div class="game-card-top"><span class="game-tag">04 · MUSIC TILES</span><span class="score" id="tilesScore">0 pts</span></div><h2>Glow tiles</h2><p>Start the beat, then tap the glowing tile before it reaches the bottom.</p><div class="tiles-board" id="tilesBoard"></div><div class="tiles-controls"><button class="sound-btn" id="startTiles">▶ Start game</button><span id="tilesCombo">Combo ×0</span></div><div class="game-feedback" id="tilesFeedback">Four lanes. One glowing tile at a time.</div>`;$('.games-grid').appendChild(card);renderTiles();$('#startTiles').onclick=startTiles}
let tileTimer=null,tileRow=0,tileLane=1,tileScore=0,tileCombo=0,tileRunning=false;
function renderTiles(){const board=$('#tilesBoard');if(!board)return;board.innerHTML=Array.from({length:24},(_,i)=>{const row=Math.floor(i/4),lane=i%4;return `<button class="tile ${tileRunning&&row===tileRow&&lane===tileLane?'falling':''}" data-tile-row="${row}" data-tile-lane="${lane}"></button>`}).join('')}
function startTiles(){if(tileTimer)clearInterval(tileTimer);tileRunning=true;tileRow=0;tileLane=Math.floor(Math.random()*4);tileScore=0;tileCombo=0;$('#tilesScore').textContent='0 pts';$('#tilesCombo').textContent='Combo ×0';$('#startTiles').textContent='■ Stop game';$('#tilesFeedback').textContent='Tap the glowing tile!';renderTiles();tileTimer=setInterval(()=>{tileRow++;if(tileRow>5){tileRow=0;tileLane=Math.floor(Math.random()*4);tileCombo=0;$('#tilesCombo').textContent='Combo ×0'}renderTiles()},480);}
document.addEventListener('click',e=>{const tile=e.target.closest('[data-tile-row]');if(!tile||!tileRunning)return;const hit=+tile.dataset.tileRow===tileRow&&+tile.dataset.tileLane===tileLane;if(hit){tileScore+=10+tileCombo*2;tileCombo++;$('#tilesScore').textContent=`${tileScore} pts`;$('#tilesCombo').textContent=`Combo ×${tileCombo}`;tone([261.63,329.63,392,523.25][tileLane],.18,'triangle',0,.1);tileRow=0;tileLane=Math.floor(Math.random()*4);renderTiles()}else{$('#tilesFeedback').textContent='Miss! Wait for the glow at the bottom.';tileCombo=0;$('#tilesCombo').textContent='Combo ×0'}});
const originalStartTiles=()=>{if(tileRunning){tileRunning=false;clearInterval(tileTimer);tileTimer=null;$('#startTiles').textContent='▶ Start game';$('#tilesFeedback').textContent='Ready when you are.';renderTiles()}else startTiles()};
load();makeGameUpgrades();
$('#startTiles').onclick=originalStartTiles;
$('#playChord').onclick=()=>{resetAnswerButtons('[data-answer]');window.currentChord=Math.random()>.5?'major':'minor';playChord(window.currentChord);$('#pitchFeedback').textContent='Now choose the feeling you heard.'};$('#playInterval').onclick=()=>{resetAnswerButtons('[data-interval]');window.currentInterval=Math.random()>.5?'step':'leap';tone(261.63,.42,'sine',0,.12);tone(window.currentInterval==='step'?293.66:392,.58,'sine',.58,.12);$('#intervalFeedback').textContent='Which distance did you hear?'};
// Clearer, louder ear-training rounds with exact interval choices.
const intervalChoices=[{id:'m2',label:'Minor 2nd',ratio:16/15},{id:'M3',label:'Major 3rd',ratio:5/4},{id:'P5',label:'Perfect 5th',ratio:3/2},{id:'octave',label:'Octave',ratio:2}];
function setupIntervalGame(){const row=$('.interval-answers');if(!row)return;row.innerHTML=intervalChoices.map(x=>`<button data-interval="${x.id}">${x.label}</button>`).join('')}
function playLoudInterval(){resetAnswerButtons('[data-interval]');const choice=intervalChoices[Math.floor(Math.random()*intervalChoices.length)];window.currentInterval=choice.id;const root=220;tone(root,.82,'sine',0,.38);tone(root*choice.ratio,1.05,'sine',.95,.38);$('#intervalFeedback').textContent='Which exact interval did you hear? You heard both notes.'}
function playLoudChord(kind){const root=kind==='major'?220:196;const third=kind==='major'?275.0:232.8;const fifth=kind==='major'?330:293.99;[root,third,fifth].forEach((f,i)=>tone(f,1.15,'triangle',i*.25,.34));tone(root/2,1.1,'sine',0,.2)}
playChord=playLoudChord;
$('#playChord').onclick=()=>{resetAnswerButtons('[data-answer]');window.currentChord=Math.random()>.5?'major':'minor';playChord(window.currentChord);$('#pitchFeedback').textContent='Now choose the feeling you heard.'};$('#playInterval').onclick=playLoudInterval;
function triggerTileLane(lane){if(!tileRunning)return;const hit=lane===tileLane&&tileRow>=5;if(hit){tileScore+=10+tileCombo*2;tileCombo++;$('#tilesScore').textContent=`${tileScore} pts`;$('#tilesCombo').textContent=`Combo ×${tileCombo}`;$('#tilesFeedback').textContent='Perfect hit!';tone([261.63,329.63,392,523.25][lane],.22,'triangle',0,.22);tileRow=0;tileLane=Math.floor(Math.random()*4);renderTiles()}else{tileCombo=0;$('#tilesCombo').textContent='Combo ×0';$('#tilesFeedback').textContent=tileRow<5?'Wait for the tile to reach the bottom line.':'Miss! Follow the glowing lane.'}}
window.addEventListener('keydown',e=>{const lane={a:0,s:1,d:2,f:3}[e.key.toLowerCase()];if(tileRunning&&lane!==undefined){e.preventDefault();triggerTileLane(lane)}});
function enhancePlayableKeys(){const p=$('#playableInstrument');if(!p)return;const x=instruments[state.instrument];if(x.type==='drums')return;const notes=[261.63,293.66,329.63,349.23,392,440,493.88,523.25,587.33,659.25,698.46,783.99];p.innerHTML=`<div class="piano"><div class="piano-label">${x.name.toUpperCase()} · PLAY WITH A S D F G H J K</div>${notes.map((n,i)=>`<button class="piano-key ${[1,3,6,8,10].includes(i)?'black':''}" data-freq="${n}" data-key="${String.fromCharCode(65+(i%8))}">${String.fromCharCode(65+(i%8))}</button>`).join('')}</div>`}
const originalSetInstrument=setInstrument;setInstrument=i=>{originalSetInstrument(i);enhancePlayableKeys()};setupIntervalGame();enhancePlayableKeys();
$('#playChord').textContent='▶ Hear full chord';$('#playInterval').querySelector('b').textContent='Play both notes';
// Capture tile clicks before the original click delegate so only bottom-line hits score.
document.addEventListener('click',e=>{const tile=e.target.closest('[data-tile-row]');if(tile){e.stopImmediatePropagation();triggerTileLane(+tile.dataset.tileLane)}},true);
const identifyNotes=[['C',261.63],['D',293.66],['E',329.63],['F',349.23],['G',392],['A',440],['B',493.88]];let identifyTarget=null,identifyScore=0;
function makeIdentifyNotes(){const card=document.createElement('section');card.className='card game-card identify-game';card.innerHTML=`<div class="game-card-top"><span class="game-tag">05 · NOTE MEMORY</span><span class="score" id="identifyScore">0 pts</span></div><h2>Identify the notes</h2><p>Hear one clear note, then choose its letter. Replay it whenever you need.</p><button class="sound-btn" id="playIdentify">▶ Play a note</button><div class="note-answers" id="noteAnswers">${identifyNotes.map(n=>`<button data-note-answer="${n[0]}">${n[0]}</button>`).join('')}</div><div class="game-feedback" id="identifyFeedback">Press play to begin a round.</div><button class="reset-game" id="resetIdentify">↻ New round</button>`;$('.games-grid').appendChild(card);$('#playIdentify').onclick=playIdentify;$('#resetIdentify').onclick=resetIdentify;playIdentify()}
function playIdentify(){resetAnswerButtons('[data-note-answer]');identifyTarget=identifyNotes[Math.floor(Math.random()*identifyNotes.length)];tone(identifyTarget[1],.9,'sine',0,.38);$('#identifyFeedback').textContent='Which note did you hear?'}
function resetIdentify(){identifyTarget=null;resetAnswerButtons('[data-note-answer]');$('#identifyFeedback').textContent='Press play to begin a round.'}
document.addEventListener('click',e=>{const answer=e.target.closest('[data-note-answer]');if(!answer||!identifyTarget)return;const correct=answer.dataset.noteAnswer===identifyTarget[0];answer.classList.add(correct?'correct':'wrong');if(correct){identifyScore+=10;$('#identifyScore').textContent=`${identifyScore} pts`;$('#identifyFeedback').textContent='Correct! New note ready.'}else $('#identifyFeedback').textContent=`Not quite—listen again for the ${identifyTarget[0]} note.`});
makeIdentifyNotes();
function shareProject(){const json=JSON.stringify(state,null,2);const fileName=`${state.projectName.replaceAll(' ','-').toLowerCase()}.json`;const file=new File([json],fileName,{type:'application/json'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){navigator.share({title:`${state.projectName} · Neon Jam Lab`,text:'Listen to my Neon Jam Lab project!',files:[file]}).then(()=>toast('Project ready to share')).catch(err=>{if(err.name!=='AbortError')toast('Share was cancelled')});return}if(navigator.clipboard){navigator.clipboard.writeText(json).then(()=>toast('Project copied — paste it to a friend')).catch(()=>exportProject())}else exportProject()}
function addShareButton(){const actions=$('.top-actions');if(!actions||$('#shareBtn'))return;const b=document.createElement('button');b.id='shareBtn';b.className='share-btn';b.innerHTML='↗ Share';b.title='Export and share this project';b.onclick=shareProject;actions.insertBefore(b,$('#exportBtn'))}
addShareButton();
// Relative-pitch mode: establish C4 first, then replay the same target as often as needed.
function playRelativeIdentify(){if(!identifyTarget)identifyTarget=identifyNotes[Math.floor(Math.random()*identifyNotes.length)];resetAnswerButtons('[data-note-answer]');tone(261.63,.62,'sine',0,.42);tone(identifyTarget[1],.88,'sine',.78,.42);$('#identifyFeedback').textContent='C4 first, then the target note. Replay as many times as you like.';$('#playIdentify').textContent='↻ Replay C4 + target'}
function newRelativeIdentify(){identifyTarget=identifyNotes[Math.floor(Math.random()*identifyNotes.length)];resetAnswerButtons('[data-note-answer]');$('#identifyFeedback').textContent='Press play to hear C4, then your target note.';$('#playIdentify').textContent='▶ Play C4 + target'}
if($('#playIdentify')){$('#playIdentify').onclick=playRelativeIdentify;$('#resetIdentify').onclick=newRelativeIdentify;newRelativeIdentify()}
function openTrackPicker(){if($('#trackPicker'))return;const modal=document.createElement('div');modal.id='trackPicker';modal.className='track-picker-backdrop';modal.innerHTML=`<div class="track-picker card"><div class="track-picker-head"><div><span class="label">ADD TO YOUR JAM</span><h2>Choose an instrument</h2><p>Pick a sound to create a new playable track.</p></div><button class="close-picker" aria-label="Close">×</button></div><div class="track-instrument-grid">${instruments.map((x,i)=>`<button class="track-instrument" data-track-inst="${i}"><span style="color:${x.color}">${x.icon}</span><b>${x.name}</b><small>${x.type}</small></button>`).join('')}</div><div class="picker-piano" id="pickerPiano"><span>Choose a keyboard instrument to preview its keys</span></div></div>`;document.body.appendChild(modal);modal.querySelector('.close-picker').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()});modal.querySelectorAll('[data-track-inst]').forEach(b=>b.onclick=()=>addInstrumentTrack(+b.dataset.trackInst));}
function addInstrumentTrack(index){const x=instruments[index];state.tracks.push([x.name,x.name,x.icon]);renderTracks();setInstrument(index);save();$('#trackPicker')?.remove();toast(`${x.name} added as a new track`)}
$('#addTrackBtn').onclick=openTrackPicker;
const baseOpenTrackPicker=openTrackPicker;openTrackPicker=()=>{baseOpenTrackPicker();const p=$('#pickerPiano');if(!p)return;p.innerHTML=`<span class="picker-note-label">PLAY THE PIANO PREVIEW</span><div class="picker-keys">${[261.63,293.66,329.63,349.23,392,440,493.88,523.25].map((f,i)=>`<button class="picker-piano-key" data-picker-freq="${f}">${String.fromCharCode(65+i)}</button>`).join('')}</div>`};$('#addTrackBtn').onclick=openTrackPicker;document.addEventListener('click',e=>{const key=e.target.closest('[data-picker-freq]');if(key){tone(+key.dataset.pickerFreq,.55,'sine',0,.2);key.classList.add('pressed');setTimeout(()=>key.classList.remove('pressed'),180)}});
// Correct piano order: C D E F G A B C, with the black keys between C-D, D-E, F-G, G-A, A-B.
const whitePiano=[['C4',261.63,'A'],['D4',293.66,'S'],['E4',329.63,'D'],['F4',349.23,'F'],['G4',392,'G'],['A4',440,'H'],['B4',493.88,'J'],['C5',523.25,'K']];const blackPiano=[['C#4',277.18,12.5,'W'],['D#4',311.13,25,'E'],['F#4',369.99,50,'T'],['G#4',415.30,62.5,'Y'],['A#4',466.16,75,'U']];
function correctPianoMarkup(name){return `<div class="correct-piano"><div class="piano-label">${name.toUpperCase()} · WHITE KEYS C D E F G A B C · COMPUTER KEYS A S D F G H J K</div><div class="white-key-row">${whitePiano.map(x=>`<button class="correct-white-key" data-freq="${x[1]}" data-key="${x[2]}"><span>${x[2]}</span><small>${x[0]}</small></button>`).join('')}</div><div class="black-key-row">${blackPiano.map(x=>`<button class="correct-black-key" style="left:${x[2]}%" data-freq="${x[1]}" data-key="${x[3]}">${x[3]}</button>`).join('')}</div></div>`}
function enhancePlayableKeys(){const p=$('#playableInstrument');if(!p)return;const x=instruments[state.instrument];if(x.type==='drums')return;p.innerHTML=correctPianoMarkup(x.name)}
playNote=(freq,type='sine')=>tone(freq,.65,type,0,.28);
document.addEventListener('click',e=>{const key=e.target.closest('.correct-white-key,.correct-black-key');if(key){playNote(+key.dataset.freq,instruments[state.instrument].type==='strings'?'triangle':'sine');key.classList.add('played');setTimeout(()=>key.classList.remove('played'),180)}});
const pickerWithCorrectKeys=openTrackPicker;openTrackPicker=()=>{pickerWithCorrectKeys();const p=$('#pickerPiano');if(p)p.innerHTML=correctPianoMarkup('PIANO PREVIEW')};$('#addTrackBtn').onclick=openTrackPicker;
function instrumentVoice(freq,kind,volume=.2,duration=.8,when=0,filterType=null){const c=audio(),osc=c.createOscillator(),gain=c.createGain();osc.type=kind;osc.frequency.setValueAtTime(freq,c.currentTime+when);gain.gain.setValueAtTime(.0001,c.currentTime+when);gain.gain.exponentialRampToValueAtTime(volume,c.currentTime+when+.025);gain.gain.exponentialRampToValueAtTime(.0001,c.currentTime+when+duration);if(filterType){const filter=c.createBiquadFilter();filter.type=filterType;filter.frequency.value=filterType==='lowpass'?2400:180;osc.connect(filter).connect(gain).connect(c.destination)}else osc.connect(gain).connect(c.destination);osc.start(c.currentTime+when);osc.stop(c.currentTime+when+duration+.05)}
function playInstrumentSound(freq){const x=instruments[state.instrument],name=x.name.toLowerCase();switch(x.type){case'piano':instrumentVoice(freq,'triangle',.3,.95);instrumentVoice(freq*2,'sine',.07,.7,.01);break;case'guitar':instrumentVoice(freq,'sawtooth',.25,1.15,0,'lowpass');instrumentVoice(freq*2,name.includes('electric')?'square':'triangle',.045,.65,.015,'highpass');break;case'bass':instrumentVoice(freq/2,'sawtooth',.34,1.05,0,'lowpass');break;case'drums':{const c=audio(),buffer=c.createBuffer(1,c.sampleRate*.24,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const src=c.createBufferSource(),g=c.createGain();src.buffer=buffer;g.gain.setValueAtTime(.32,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.24);src.connect(g).connect(c.destination);src.start();tone(Math.max(70,freq/3),.18,'sine',0,.18);break}case'harp':instrumentVoice(freq,'triangle',.32,1.3);instrumentVoice(freq*2,'sine',.08,.8,.01);break;case'strings':instrumentVoice(freq,'sawtooth',.24,1.25,0,'lowpass');instrumentVoice(freq*1.005,'triangle',.12,1.1,.02,'lowpass');break;case'wind':if(name.includes('flute')){instrumentVoice(freq,'sine',.3,1.05,0,'lowpass');instrumentVoice(freq*2,'sine',.035,.8,.02,'lowpass')}else{instrumentVoice(freq,'square',.22,.9,0,'lowpass');instrumentVoice(freq*2,'triangle',.06,.7,.02,'lowpass')}break;case'voice':instrumentVoice(freq,'sawtooth',.2,1,0,'lowpass');instrumentVoice(freq*1.5,'sine',.06,.8,.02,'lowpass');break;default:instrumentVoice(freq,'square',.25,.8)}}
playNote=(freq)=>playInstrumentSound(freq);
const renderedPlayable=renderPlayable;renderPlayable=()=>{renderedPlayable();enhancePlayableKeys()};enhancePlayableKeys();
if($('.identify-game')){$('.identify-game h2').textContent='Note identification';$('.identify-game .game-tag').textContent='05 · NOTE IDENTIFICATION';$('.identify-game p').textContent='Hear C4 first, then identify the target note by ear. Replay the pair whenever you need.'}
